id: GoogleAppsTest
version: -1
name: GoogleAppsTest
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: aff522d9-9e56-476d-8966-a96f5fd4a9db
    type: start
    task:
      id: aff522d9-9e56-476d-8966-a96f5fd4a9db
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 9d8a791f-c5fb-4582-84d4-5cd7f5e8afb8
    type: regular
    task:
      id: 9d8a791f-c5fb-4582-84d4-5cd7f5e8afb8
      version: -1
      name: Start clean
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
      - "7"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: 02b5dcaf-1656-4298-8f75-6c0f8850c90c
    type: regular
    task:
      id: 02b5dcaf-1656-4298-8f75-6c0f8850c90c
      version: -1
      name: List all users
      script: GoogleApps API|||googleapps-list-users
      type: regular
      iscommand: true
      brand: GoogleApps API
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      custom-field-mask: {}
      customer: {}
      domain: {}
      event: {}
      max-results: {}
      projection: {}
      query: {}
      show-deleted: {}
      sort-order: {}
      token: {}
      view-type-public-domain: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 515
        }
      }
  "3":
    id: "3"
    taskid: a4dd13cf-2166-4234-8ad7-0f0407c17c49
    type: regular
    task:
      id: a4dd13cf-2166-4234-8ad7-0f0407c17c49
      version: -1
      name: Get specific user
      script: GoogleApps API|||googleapps-get-user
      type: regular
      iscommand: true
      brand: GoogleApps API
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      custom-field-mask: {}
      projection: {}
      user-key:
        complex:
          root: Account
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: Account.UserName
                iscontext: true
              right:
                value:
                  simple: test
          transformers:
          - operator: general.getField
            args:
              field:
                value:
                  simple: Email
          - operator: general.getField
            args:
              field:
                value:
                  simple: Address
      view-type-public-domain: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 690
        }
      }
  "4":
    id: "4"
    taskid: 6b1faaae-2b38-4f22-8647-0ff81166f0d8
    type: regular
    task:
      id: 6b1faaae-2b38-4f22-8647-0ff81166f0d8
      version: -1
      name: Create UUID
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      contextKey: {}
      date: {}
      dateFormat: {}
      hoursAgo: {}
      minutesAgo: {}
      monthsAgo: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 865
        }
      }
  "5":
    id: "5"
    taskid: 618e0494-dce2-4541-8aa0-0ce987ffec5b
    type: regular
    task:
      id: 618e0494-dce2-4541-8aa0-0ce987ffec5b
      version: -1
      name: Create new user
      script: GoogleApps API|||googleapps-insert-user
      type: regular
      iscommand: true
      brand: GoogleApps API
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      email:
        simple: JohnS${TimeNowUnix}@demistodev.com
      family-name:
        simple: Smith
      given-name:
        simple: John
      password:
        simple: johnpass1!
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1040
        }
      }
  "6":
    id: "6"
    taskid: ec9aa9ea-8721-4544-83f4-ce9be74ce83a
    type: regular
    task:
      id: ec9aa9ea-8721-4544-83f4-ce9be74ce83a
      version: -1
      name: Delete User
      script: GoogleApps API|||googleapps-delete-user
      type: regular
      iscommand: true
      brand: GoogleApps API
    nexttasks:
      '#none#':
      - "11"
      - "12"
      - "13"
    scriptarguments:
      user-key:
        complex:
          root: Account
          filters:
          - - operator: string.startWith
              left:
                value:
                  simple: Account.Email.Address
                iscontext: true
              right:
                value:
                  simple: JohnS
          transformers:
          - operator: general.getField
            args:
              field:
                value:
                  simple: Email
          - operator: general.getField
            args:
              field:
                value:
                  simple: Address
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1215
        }
      }
  "7":
    id: "7"
    taskid: c4149303-c745-408e-8e2c-8db659e7f681
    type: title
    task:
      id: c4149303-c745-408e-8e2c-8db659e7f681
      version: -1
      name: Gmail Commands
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 370
        }
      }
  "8":
    id: "8"
    taskid: 1f2d6b7b-579c-4239-836a-3a3cd9211cd4
    type: title
    task:
      id: 1f2d6b7b-579c-4239-836a-3a3cd9211cd4
      version: -1
      name: User Commands
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "9":
    id: "9"
    taskid: 451bd7f3-0a5b-4ffe-819d-bc5540eea282
    type: regular
    task:
      id: 451bd7f3-0a5b-4ffe-819d-bc5540eea282
      version: -1
      name: Search emails with attachments
      script: GoogleApps API|||googleapps-gmail-search
      type: regular
      iscommand: true
      brand: GoogleApps API
    nexttasks:
      '#none#':
      - "10"
      - "14"
    scriptarguments:
      fields: {}
      include-spam-trash: {}
      labels-ids: {}
      max-results:
        simple: "10"
      page-token: {}
      query:
        simple: has:attachment
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 515
        }
      }
  "10":
    id: "10"
    taskid: 05ac34db-6730-4ce8-89c9-e2065f888dfb
    type: regular
    task:
      id: 05ac34db-6730-4ce8-89c9-e2065f888dfb
      version: -1
      name: Get mail with attachment
      script: GoogleApps API|||googleapps-gmail-get-attachment
      type: regular
      iscommand: true
      brand: GoogleApps API
    scriptarguments:
      attachment-id:
        complex:
          root: Email
          filters:
          - - operator: general.isNotEmpty
              left:
                value:
                  simple: Email.Attachments
                iscontext: true
          transformers:
          - operator: general.e56a7467-e156-4296-8c87-25b64aa20b3a
          - operator: general.getField
            args:
              field:
                value:
                  simple: Attachments
          - operator: general.e56a7467-e156-4296-8c87-25b64aa20b3a
          - operator: general.getField
            args:
              field:
                value:
                  simple: ID
      message-id:
        complex:
          root: Email
          filters:
          - - operator: general.isNotEmpty
              left:
                value:
                  simple: Email.Attachments
                iscontext: true
          transformers:
          - operator: general.e56a7467-e156-4296-8c87-25b64aa20b3a
          - operator: general.getField
            args:
              field:
                value:
                  simple: ID
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 690
        }
      }
  "11":
    id: "11"
    taskid: e3e81383-abcd-4c59-8ef5-e999b1160333
    type: regular
    task:
      id: e3e81383-abcd-4c59-8ef5-e999b1160333
      version: -1
      name: Get chrome devices
      script: GoogleApps API|||googleapps-get-chrome-devices-for-user
      type: regular
      iscommand: true
      brand: GoogleApps API
    scriptarguments:
      customerId:
        simple: my_customer
      query: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
  "12":
    id: "12"
    taskid: a3f03b7e-caa8-46ee-8d8e-3d00f57f37f6
    type: regular
    task:
      id: a3f03b7e-caa8-46ee-8d8e-3d00f57f37f6
      version: -1
      name: Get Devices
      script: GoogleApps API|||googleapps-get-devices-for-user
      type: regular
      iscommand: true
      brand: GoogleApps API
    scriptarguments:
      customerId: {}
      query: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1390
        }
      }
  "13":
    id: "13"
    taskid: f4a6c845-362e-405b-8e6d-b634f0d31ba5
    type: regular
    task:
      id: f4a6c845-362e-405b-8e6d-b634f0d31ba5
      version: -1
      name: Get Tokens
      script: GoogleApps API|||googleapps-get-tokens-for-user
      type: regular
      iscommand: true
      brand: GoogleApps API
    scriptarguments:
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1390
        }
      }
  "14":
    id: "14"
    taskid: 752d5ed6-87d9-4e06-806a-8699a793d172
    type: regular
    task:
      id: 752d5ed6-87d9-4e06-806a-8699a793d172
      version: -1
      name: Get Email data
      script: GoogleApps API|||googleapps-gmail-get-mail
      type: regular
      iscommand: true
      brand: GoogleApps API
    scriptarguments:
      fields: {}
      format: {}
      message-id:
        complex:
          root: Email
          accessor: '[0]'
          transformers:
          - operator: general.getField
            args:
              field:
                value:
                  simple: ID
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 690
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 1455,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
