id: GmailTest
version: -1
name: GmailTest
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: aff522d9-9e56-476d-8966-a96f5fd4a9db
    type: start
    task:
      id: aff522d9-9e56-476d-8966-a96f5fd4a9db
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 9d8a791f-c5fb-4582-84d4-5cd7f5e8afb8
    type: regular
    task:
      id: 9d8a791f-c5fb-4582-84d4-5cd7f5e8afb8
      version: -1
      name: Start clean
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
      - "7"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: 7820bb6b-0b10-4a56-83e9-0632c7c732e3
    type: regular
    task:
      id: 7820bb6b-0b10-4a56-83e9-0632c7c732e3
      version: -1
      name: List all users
      script: Gmail|||gmail-list-users
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      custom-field-mask: {}
      customer: {}
      domain: {}
      event: {}
      max-results: {}
      projection: {}
      query: {}
      show-deleted: {}
      sort-order: {}
      token: {}
      view-type-public-domain: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
  "3":
    id: "3"
    taskid: e83862fc-822f-45af-8050-6885158dcb77
    type: regular
    task:
      id: e83862fc-822f-45af-8050-6885158dcb77
      version: -1
      name: Get specific user
      script: Gmail|||gmail-get-user
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      custom-field-mask: {}
      projection: {}
      user-key:
        complex:
          root: Account
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: Account.UserName
                iscontext: true
              right:
                value:
                  simple: test
          transformers:
          - operator: general.getField
            args:
              field:
                value:
                  simple: Email
          - operator: general.getField
            args:
              field:
                value:
                  simple: Address
      view-type-public-domain: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
  "4":
    id: "4"
    taskid: 6b1faaae-2b38-4f22-8647-0ff81166f0d8
    type: regular
    task:
      id: 6b1faaae-2b38-4f22-8647-0ff81166f0d8
      version: -1
      name: Create UUID
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      contextKey: {}
      date: {}
      dateFormat: {}
      hoursAgo: {}
      minutesAgo: {}
      monthsAgo: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "5":
    id: "5"
    taskid: 9a660df8-640f-4c90-8604-f537775434ff
    type: regular
    task:
      id: 9a660df8-640f-4c90-8604-f537775434ff
      version: -1
      name: Create new user
      script: Gmail|||gmail-create-user
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      email:
        simple: JohnS${TimeNowUnix}@demistodev.com
      family-name:
        simple: Smith
      first-name:
        simple: John
      password:
        simple: johnpass1!
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "6":
    id: "6"
    taskid: b43589f0-7afd-4167-833b-db0dd03bfb8c
    type: regular
    task:
      id: b43589f0-7afd-4167-833b-db0dd03bfb8c
      version: -1
      name: Delete User
      script: Gmail|||gmail-delete-user
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      user-key:
        complex:
          root: Account
          filters:
          - - operator: string.startWith
              left:
                value:
                  simple: Account.Email.Address
                iscontext: true
              right:
                value:
                  simple: JohnS
          transformers:
          - operator: general.getField
            args:
              field:
                value:
                  simple: Email
          - operator: general.getField
            args:
              field:
                value:
                  simple: Address
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
  "7":
    id: "7"
    taskid: c4149303-c745-408e-8e2c-8db659e7f681
    type: title
    task:
      id: c4149303-c745-408e-8e2c-8db659e7f681
      version: -1
      name: Gmail Commands
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "8":
    id: "8"
    taskid: 1f2d6b7b-579c-4239-836a-3a3cd9211cd4
    type: title
    task:
      id: 1f2d6b7b-579c-4239-836a-3a3cd9211cd4
      version: -1
      name: User Commands
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "9":
    id: "9"
    taskid: 5da9c388-670b-4a1b-82bd-fed3a1ac0cb6
    type: regular
    task:
      id: 5da9c388-670b-4a1b-82bd-fed3a1ac0cb6
      version: -1
      name: Search emails with attachments
      script: Gmail|||gmail-search
      type: regular
      iscommand: true
      brand: Gmail
    nexttasks:
      '#none#':
      - "10"
      - "14"
    scriptarguments:
      after: {}
      before: {}
      fields: {}
      filename: {}
      from: {}
      in: {}
      include-spam-trash: {}
      label: {}
      labels-ids: {}
      max-results:
        simple: "10"
      page-token: {}
      query:
        simple: has:attachment
      subject: {}
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 515
        }
      }
  "10":
    id: "10"
    taskid: fbd7cf70-ab59-474b-8a2c-d00a75715f0a
    type: regular
    task:
      id: fbd7cf70-ab59-474b-8a2c-d00a75715f0a
      version: -1
      name: Get mail with attachment
      script: Gmail|||gmail-get-attachments
      type: regular
      iscommand: true
      brand: Gmail
    scriptarguments:
      message-id:
        complex:
          root: Email
          filters:
          - - operator: general.isNotEmpty
              left:
                value:
                  simple: Email.Attachments
                iscontext: true
          transformers:
          - operator: general.GetFirstObject
          - operator: general.getField
            args:
              field:
                value:
                  simple: ID
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
  "13":
    id: "13"
    taskid: 2dbed4ad-0f09-425f-8a93-34d4972dbdd2
    type: regular
    task:
      id: 2dbed4ad-0f09-425f-8a93-34d4972dbdd2
      version: -1
      name: Get Tokens
      script: Gmail|||gmail-get-tokens-for-user
      type: regular
      iscommand: true
      brand: Gmail
    scriptarguments:
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
  "14":
    id: "14"
    taskid: 70b2464e-4a0a-4a6f-8fef-f9a5e3c04c15
    type: regular
    task:
      id: 70b2464e-4a0a-4a6f-8fef-f9a5e3c04c15
      version: -1
      name: Get Email data
      script: Gmail|||gmail-get-mail
      type: regular
      iscommand: true
      brand: Gmail
    scriptarguments:
      format: {}
      message-id:
        complex:
          root: Email
          accessor: '[0]'
          transformers:
          - operator: general.getField
            args:
              field:
                value:
                  simple: ID
      user-key:
        simple: admin@demistodev.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 690
        }
      }
  "16":
    id: "16"
    taskid: d6fcde30-3dc9-4c5e-89d9-77e02ba26e07
    type: regular
    task:
      id: d6fcde30-3dc9-4c5e-89d9-77e02ba26e07
      version: -1
      name: Search all mailboxes
      script: Gmail|||gmail-search-all-mailboxes
      type: regular
      iscommand: true
      brand: Gmail
    scriptarguments:
      after:
        simple: 2018/1/20
      before:
        simple: 2018/1/30
      fields: {}
      filename: {}
      from: {}
      in: {}
      include-spam-trash: {}
      label: {}
      labels-ids: {}
      max-results:
        simple: "2"
      page-token: {}
      query:
        simple: has:attachment
      subject: {}
      to: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 515
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 1455,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
