id: Detonate URL - Generic
version: -1
name: Detonate URL - Generic
fromversion: 4.0.0
description: Detonate file through active integrations that support file detonation
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 73eadb3f-61fa-41d5-87b3-6d6a67a04e63
    type: start
    task:
      id: 73eadb3f-61fa-41d5-87b3-6d6a67a04e63
      version: -1
      name: ""
      description: Playbook start point
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
      - "13"
      - "12"
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 9db19651-009c-468f-80b3-c58efea96ed2
    type: title
    task:
      id: 9db19651-009c-468f-80b3-c58efea96ed2
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 14465d51-f9b2-46bd-8e35-22fb08ca86c6
    type: playbook
    task:
      id: 14465d51-f9b2-46bd-8e35-22fb08ca86c6
      version: -1
      name: Detonate URL - ThreatGrid
      playbookName: Detonate URL - ThreatGrid
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 920,
          "y": 195
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 9b945f0a-c0e4-4b17-8456-11b701ae35d9
    type: playbook
    task:
      id: 9b945f0a-c0e4-4b17-8456-11b701ae35d9
      version: -1
      name: Detonate URL - McAfee ATD
      playbookName: Detonate URL - McAfee ATD
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 195
        }
      }
    note: false
  "13":
    id: "13"
    taskid: f914c21c-c9dc-43e1-8bba-0d482fdfb851
    type: playbook
    task:
      id: f914c21c-c9dc-43e1-8bba-0d482fdfb851
      version: -1
      name: Detonate URL - JoeSecurity
      playbookName: Detonate URL - JoeSecurity
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      URL:
        complex:
          root: URL
          accessor: Data
      comments: {}
      internet-access:
        simple: "True"
      interval:
        simple: "1"
      report-file-type:
        simple: html
      systems: {}
      timeout:
        simple: "15"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
  "14":
    id: "14"
    taskid: f497277e-c437-4727-8983-c915eb42682c
    type: playbook
    task:
      id: f497277e-c437-4727-8983-c915eb42682c
      version: -1
      name: Detonate URL - CrowdStrike
      playbookName: Detonate URL - CrowdStrike
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 1660,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: EntryID
  value:
    complex:
      root: File
      accessor: EntryID
  required: false
  description: Entry ID of file to be detonated
- key: File
  value:
    complex:
      root: File
  required: false
  description: File object of file to be detonated
outputs:
- contextPath: DBotScore
  description: The Indicator's object
  type: unknown
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
- contextPath: File.SHA1
  description: SHA1 of the file
  type: string
- contextPath: File.MD5
  description: MD5 of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File
  description: The File's object
  type: unknown
- contextPath: File.SHA256
  description: SHA256 of the file
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: File.Type
  description: File type e.g. "PE" (only in case of report type=json)
  type: string
- contextPath: File.Size
  description: File size (only in case of report type=json)
  type: number
- contextPath: File.Name
  description: Filename (only in case of report type=json)
  type: string
releaseNotes: "New generic detonation playbook for URL"