id: detonate_url_-_crowdstrike
version: -1
name: Detonate URL - CrowdStrike
fromversion: 4.0.0
description: Detonate one or more files using the Wildfire integration. This playbook
  returns relevant reports to the War Room and file reputations to the context data.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 22ad464c-0c80-476b-8c6b-063135760ea0
    type: start
    task:
      id: 22ad464c-0c80-476b-8c6b-063135760ea0
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 7f5ff3a5-55e0-4aee-8c7d-d75e539e7702
    type: condition
    task:
      id: 7f5ff3a5-55e0-4aee-8c7d-d75e539e7702
      version: -1
      name: Is CrowdStrike enabled?
      description: |
        Verify that there is a valid instance of CrowdStrike enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: VxStream
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 589641d2-705d-4b7d-844f-2a8ab60497c8
    type: title
    task:
      id: 589641d2-705d-4b7d-844f-2a8ab60497c8
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1140
        }
      }
    note: false
  "8":
    id: "8"
    taskid: e427d919-35ef-454c-8ce3-d5f32add184c
    type: regular
    task:
      id: e427d919-35ef-454c-8ce3-d5f32add184c
      version: -1
      name: CrowdStrike Scan
      description: Download the pdf report to the War Room.
      script: VxStream|||crowdstrike-scan
      type: regular
      iscommand: true
      brand: VxStream
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      file:
        complex:
          root: File
          accessor: SHA256
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 925
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 65ba03f6-41d1-49b7-8a3d-f1c5524247db
    type: regular
    task:
      id: 65ba03f6-41d1-49b7-8a3d-f1c5524247db
      version: -1
      name: CrowdStrike Upload Sample
      description: Upload samle to crowdstrike.
      script: VxStream|||crowdstrike-submit-url
      type: regular
      iscommand: true
      brand: VxStream
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      environmentID:
        complex:
          root: inputs.EnvironmentID
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 550
        }
      }
    note: false
  "14":
    id: "14"
    taskid: bb4c22c0-9471-4574-8989-67d2933b1982
    type: condition
    task:
      id: bb4c22c0-9471-4574-8989-67d2933b1982
      version: -1
      name: Is there a URL to detonate?
      description: Checks whether there's a file to detonate.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
  "16":
    id: "16"
    taskid: e73b0e53-2b56-4c8c-869d-e380178e3934
    type: playbook
    task:
      id: e73b0e53-2b56-4c8c-869d-e380178e3934
      version: -1
      name: GenericPolling
      description: |-
        Use as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continually running the command in Step #2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Ids:
        complex:
          root: File
          accessor: SHA256
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: file
      PollingCommandName:
        simple: crowdstrike-scan
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: File(val.state === 'NO_CONTENT').hash
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 740
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1155,
        "width": 677.5,
        "x": 162.5,
        "y": 50
      }
    }
  }
inputs:
- key: URL
  value:
    complex:
      root: URL
      accessor: Data
  required: false
  description: URL to detonate.
- key: EnvironmentID
  value:
    simple: "100"
  required: false
  description: Environment ID to submit the file to. To get all IDs run the crowdstrike-get-environments
    command.
- key: Interval
  value:
    simple: "5"
  required: false
  description: Polling frequency - how often the polling command should run (minutes)
- key: Timeout
  value:
    simple: "30"
  required: false
  description: How much time to wait before a timeout occurs  (minutes)
outputs:
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Malicious
  description: The File malicious description
  type: unknown
- contextPath: File.Type
  description: File type e.g. "PE"
  type: string
- contextPath: File.Size
  description: File size
  type: number
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.Name
  description: Filename
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File
  description: The File object
  type: unknown
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: DBotScore
  description: The DBotScore object
  type: unknown
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
releaseNotes: "-"