id: Detonate URL - McAfee ATD
version: -1
name: Detonate URL - McAfee ATD
fromversion: 4.0.0
description: Detonates a URL using the McAfee Advanced Threat Defense sandbox integration.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 08e29819-73da-4fab-8f7e-b99064f37a49
    type: start
    task:
      id: 08e29819-73da-4fab-8f7e-b99064f37a49
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 04b87e59-8390-4dfb-8ad8-1ab2daf4b667
    type: regular
    task:
      id: 04b87e59-8390-4dfb-8ad8-1ab2daf4b667
      version: -1
      name: McAfee ATD Upload URL
      description: Uploads the submission to McAfee ATD.
      script: McAfee Advanced Threat Defense|||atd-file-upload
      type: regular
      iscommand: true
      brand: McAfee Advanced Threat Defense
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      analyzeAgain: {}
      dstIp: {}
      entryID: {}
      fileName: {}
      filePriorityQ: {}
      messageId: {}
      skipTaskId: {}
      srcIp: {}
      submitType:
        simple: "1"
      url:
        complex:
          root: inputs.URL
      vmProfileList: {}
      xMode: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
  "2":
    id: "2"
    taskid: dc203162-1804-4de9-8e35-8d9fe37587e2
    type: playbook
    task:
      id: dc203162-1804-4de9-8e35-8d9fe37587e2
      version: -1
      name: GenericPolling
      description: |-
        Use as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continually running the command in Step #2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      Ids:
        complex:
          root: ATD
          filters:
          - - operator: isNotEqualNumber
              left:
                value:
                  simple: ATD.Task.taskId
                iscontext: true
              right:
                value:
                  simple: "-1"
          accessor: Task
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: taskId
      Interval:
        complex:
          root: inputs.interval
      PollingCommandArgName:
        simple: taskId
      PollingCommandName:
        simple: atd-check-status
      Timeout:
        complex:
          root: inputs.timeout
      dt:
        simple: ATD.Task(val.status != 'Completed').taskId
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 31c8e066-df56-4bf7-884e-a77c300002c2
    type: regular
    task:
      id: 31c8e066-df56-4bf7-884e-a77c300002c2
      version: -1
      name: McAfee ATD Get Report
      description: Retrieve the reports from McAfee ATD.
      script: McAfee Advanced Threat Defense|||atd-get-report
      type: regular
      iscommand: true
      brand: McAfee Advanced Threat Defense
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      jobId: {}
      taskId:
        complex:
          root: ATD
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: ATD.Task.status
                iscontext: true
              right:
                value:
                  simple: Completed
          accessor: Task
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: taskId
      threshold: {}
      type:
        simple: pdf
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
  "5":
    id: "5"
    taskid: f759fa2c-df8d-49c0-8098-aaf10a97c727
    type: condition
    task:
      id: f759fa2c-df8d-49c0-8098-aaf10a97c727
      version: -1
      name: Is there a URL to detonate?
      description: Checks that there is a URL in the playbook’s input.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 275,
          "y": 370
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 05df36f0-af05-42aa-8621-87675e7e8054
    type: title
    task:
      id: 05df36f0-af05-42aa-8621-87675e7e8054
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1420
        }
      }
    note: false
  "8":
    id: "8"
    taskid: e663cec1-26f6-44c4-85cb-b456c4b33eec
    type: condition
    task:
      id: e663cec1-26f6-44c4-85cb-b456c4b33eec
      version: -1
      name: filter taskId
      description: Checks that valid URLs only have been sent to detonation.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: ATD
                filters:
                - - operator: isNotEqualNumber
                    left:
                      value:
                        simple: ATD.Task.taskId
                      iscontext: true
                    right:
                      value:
                        simple: "-1"
                accessor: Task
                transformers:
                - operator: getField
                  args:
                    field:
                      value:
                        simple: taskId
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
  "9":
    id: "9"
    taskid: ff90cd61-0826-43d4-8924-dbdd3fbb21e7
    type: condition
    task:
      id: ff90cd61-0826-43d4-8924-dbdd3fbb21e7
      version: -1
      name: Is McAfee ATD sandbox enabled?
      description: |
        Verify that there is a valid instance of McAfee ATD enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: McAfee Advanced Threat Defense
                  - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 195
        }
      }
    note: false
  "10":
    id: "10"
    taskid: d0e454b4-5cbf-47bf-885a-107acbd3bb9f
    type: regular
    task:
      id: d0e454b4-5cbf-47bf-885a-107acbd3bb9f
      version: -1
      name: atd-check-status
      description: Updates the status of the tasks in the context.
      script: McAfee Advanced Threat Defense|||atd-check-status
      type: regular
      iscommand: true
      brand: McAfee Advanced Threat Defense
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      jobId: {}
      taskId:
        complex:
          root: ATD
          accessor: Task.taskId
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 717.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: URL
  value:
    complex:
      root: URL
      accessor: Data
  required: true
  description: URL to detonate.
- key: interval
  value:
    simple: "1"
  required: false
  description: Polling frequency - how often the polling command should run (minutes)
- key: timeout
  value:
    simple: "15"
  required: false
  description: How much time to wait before a timeout occurs (minutes)
outputs:
- contextPath: File.Size
  description: File size (only in case of report type=json)
  type: number
- contextPath: DBotScore.Indicator
  description: The indicator we tested (only in case of report type=json)
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score (only in case of report type=json)
  type: string
- contextPath: DBotScore.Score
  description: The actual score (only in case of report type=json)
  type: number
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator (only in case of report type=json)
  type: string
- contextPath: File.Name
  description: Filename (only in case of report type=json)
  type: string
- contextPath: File.Type
  description: File type e.g. "PE" (only in case of report type=json)
  type: string
- contextPath: File.MD5
  description: MD5 hash of the file (only in case of report type=json)
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file (only in case of report type=json)
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file (only in case of report type=json)
  type: string
- contextPath: File.EntryID
  description: The Entry ID of the sample
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
