id: Detonate File - Generic
version: -1
name: Detonate File - Generic
fromversion: "4.0.0"
description: Detonate file through active integrations that support file detonation
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 73eadb3f-61fa-41d5-87b3-6d6a67a04e63
    type: start
    task:
      id: 73eadb3f-61fa-41d5-87b3-6d6a67a04e63
      version: -1
      name: ""
      description: Playbook start point
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
      - "8"
      - "10"
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 9db19651-009c-468f-80b3-c58efea96ed2
    type: title
    task:
      id: 9db19651-009c-468f-80b3-c58efea96ed2
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 941ada70-74e6-42a5-8197-ff7348b8bd52
    type: playbook
    task:
      id: 941ada70-74e6-42a5-8197-ff7348b8bd52
      version: -1
      name: CrowdStrike - Detonate file
      description: Detonate one or more files using the CrowdStrike integration. This
        playbook returns relevant reports to the War Room and file reputations to
        the context data. The detonation supports the following file types - EXE,
        DLL, JAR, JS, PDF, DOC, DOCX, RTF, XLS, PPT, PPTX, XML, ZIP, VBN, SEP, XZ,
        GZ, BZ2, TAR, MHTML, SWF, LNK, URL, MSI, JTD, JTT, JTDC, JTTC, HWP, HWT, HWPX,
        BAT, HTA, PS1, VBS, WSF, JSE, VBE, CHM
      playbookName: CrowdStrike - Detonate file
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      File:
        complex:
          root: inputs.File
      environmentID:
        simple: "100"
      interval:
        simple: "5"
      timeout:
        simple: "30"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 60defe17-6a73-4236-8eb3-4ba2c8e5514b
    type: playbook
    task:
      id: 60defe17-6a73-4236-8eb3-4ba2c8e5514b
      version: -1
      name: Detonate File - JoeSecurity
      description: |-
        Detonates one or more files using the Joe Security - Joe Sandbox integration.
        Returns relevant reports to the War Room and file reputations to the context data.
        All file types are supported.
      playbookName: Detonate File - JoeSecurity
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      File:
        complex:
          root: inputs.File
      comments: {}
      internet-access:
        simple: "True"
      interval:
        simple: "1"
      report-file-type: {}
      systems: {}
      timeout:
        simple: "15"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
  "9":
    id: "9"
    taskid: e028411a-442b-4450-84eb-275082a8679a
    type: playbook
    task:
      id: e028411a-442b-4450-84eb-275082a8679a
      version: -1
      name: Detonate File - McAfee ATD
      playbookName: Detonate File - McAfee ATD
      type: playbook
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      File:
        complex:
          root: inputs.File
      interval:
        simple: "1"
      timeout:
        simple: "15"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 092742aa-8cf7-4572-8dee-d7d58a90d876
    type: playbook
    task:
      id: 092742aa-8cf7-4572-8dee-d7d58a90d876
      version: -1
      name: Detonate File - ThreatGrid
      playbookName: Detonate File - ThreatGrid
      type: playbook
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      File:
        complex:
          root: inputs.File
      FileName:
        simple: file-detonated-via-demisto
      interval:
        simple: "1"
      os: {}
      osver: {}
      private: {}
      source: {}
      tags: {}
      timeout:
        simple: "15"
      vm: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: EntryID
  value:
    complex:
      root: File
      accessor: EntryID
  required: false
  description: Entry ID of file to be detonated
- key: File
  value:
    complex:
      root: File
  required: false
  description: File object of file to be detonated
outputs:
- contextPath: DBotScore
  description: The Indicator's object
  type: unknown
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
- contextPath: File.SHA1
  description: SHA1 of the file
  type: string
- contextPath: File.MD5
  description: MD5 of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File
  description: The File's object
  type: unknown
- contextPath: File.SHA256
  description: SHA256 of the file
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: File.Type
  description: File type e.g. "PE" (only in case of report type=json)
  type: string
- contextPath: File.Size
  description: File size (only in case of report type=json)
  type: number
- contextPath: File.Name
  description: Filename (only in case of report type=json)
  type: string
releaseNotes: "-"