id: Detonate URL - CrowdStrike
version: -1
name: Detonate URL - CrowdStrike
fromversion: 4.0.0
description: Detonate one or more files using the Wildfire integration. This playbook
  returns relevant reports to the War Room and file reputations to the context data.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 29dcbc1e-0bb0-45f1-82ed-eb65b6ce039d
    type: start
    task:
      id: 29dcbc1e-0bb0-45f1-82ed-eb65b6ce039d
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 3e2a6ea9-7f88-4d10-8d29-3ed2d10eba4f
    type: condition
    task:
      id: 3e2a6ea9-7f88-4d10-8d29-3ed2d10eba4f
      version: -1
      name: Is CrowdStrike enabled?
      description: |
        Verify that there is a valid instance of CrowdStrike enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: VxStream
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
  "6":
    id: "6"
    taskid: e6a670a6-eff4-4b16-883b-f08e7d7e7bd3
    type: title
    task:
      id: e6a670a6-eff4-4b16-883b-f08e7d7e7bd3
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1140
        }
      }
    note: false
  "8":
    id: "8"
    taskid: d2a69807-063c-4773-8ae3-815dd1372cd2
    type: regular
    task:
      id: d2a69807-063c-4773-8ae3-815dd1372cd2
      version: -1
      name: CrowdStrike Scan
      description: Download the pdf report to the War Room.
      script: VxStream|||crowdstrike-scan
      type: regular
      iscommand: true
      brand: VxStream
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      file:
        complex:
          root: File
          accessor: SHA256
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 925
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 480ec5d3-087e-479d-8c29-0c70a1060ee0
    type: regular
    task:
      id: 480ec5d3-087e-479d-8c29-0c70a1060ee0
      version: -1
      name: CrowdStrike Upload Sample
      description: Upload samle to crowdstrike.
      script: VxStream|||crowdstrike-submit-url
      type: regular
      iscommand: true
      brand: VxStream
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      environmentID:
        complex:
          root: inputs.environmentID
      url:
        complex:
          root: inputs.Url
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 550
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 6ffba508-37e1-4647-88ea-265cd5475d61
    type: condition
    task:
      id: 6ffba508-37e1-4647-88ea-265cd5475d61
      version: -1
      name: Is there a url to detonate?
      description: Checks whether there's a file to detonate.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.Url
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
  "16":
    id: "16"
    taskid: b7173e60-8b5e-490f-8b16-16c4bf67fcdf
    type: playbook
    task:
      id: b7173e60-8b5e-490f-8b16-16c4bf67fcdf
      version: -1
      name: GenericPolling
      description: |-
        Use as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continually running the command in Step #2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Ids:
        complex:
          root: File
          accessor: SHA256
      Interval:
        complex:
          root: inputs.interval
      PollingCommandArgName:
        simple: file
      PollingCommandName:
        simple: crowdstrike-scan
      Timeout:
        complex:
          root: inputs.timeout
      dt:
        simple: File(val.state === 'NO_CONTENT').hash
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 740
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1155,
        "width": 677.5,
        "x": 162.5,
        "y": 50
      }
    }
  }
inputs:
- key: Url
  value:
    complex:
      root: URL
      accessor: Data
  required: false
  description: URL to detonate.
- key: environmentID
  value:
    simple: "100"
  required: false
  description: Environment ID to submit the file to. To get all IDs run the crowdstrike-get-environments
    command.
- key: interval
  value:
    simple: "5"
  required: false
  description: Polling frequency - how often the polling command should run (minutes)
- key: timeout
  value:
    simple: "30"
  required: false
  description: How much time to wait before a timeout occurs  (minutes)
outputs:
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Malicious
  description: The File malicious description
  type: unknown
- contextPath: File.Type
  description: File type e.g. "PE"
  type: string
- contextPath: File.Size
  description: File size
  type: number
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.Name
  description: Filename
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File
  description: The File object
  type: unknown
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: DBotScore
  description: The DBotScore object
  type: unknown
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
releaseNotes: "-"