id: Detonate URL - Generic
version: -1
name: Detonate URL - Generic
fromversion: 4.0.0
description: Detonate file through active integrations that support file detonation
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 73eadb3f-61fa-41d5-87b3-6d6a67a04e63
    type: start
    task:
      id: 73eadb3f-61fa-41d5-87b3-6d6a67a04e63
      version: -1
      name: ""
      description: Playbook start point
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
      - "13"
      - "12"
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 9db19651-009c-468f-80b3-c58efea96ed2
    type: title
    task:
      id: 9db19651-009c-468f-80b3-c58efea96ed2
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
  "11":
    id: "11"
    taskid: b9153231-1e6d-4646-8f96-373a34716936
    type: playbook
    task:
      id: b9153231-1e6d-4646-8f96-373a34716936
      version: -1
      name: Detonate URL - ThreatGrid
      description: Detonate one or more URLs using the Threat Grid integration. This
        playbook returns relevant reports to the War Room and URL reputations to the
        context data.
      playbookName: Detonate URL - ThreatGrid
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      FileName:
        simple: file-detonated-via-demisto
      interval:
        simple: "1"
      os: {}
      osver: {}
      private: {}
      source: {}
      tags: {}
      timeout:
        simple: "15"
      url:
        complex:
          root: inputs.URL
          accessor: Data
      vm: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 920,
          "y": 195
        }
      }
    note: false
  "12":
    id: "12"
    taskid: a90cd865-1dbe-46ba-8cd9-65a3b13c74d6
    type: playbook
    task:
      id: a90cd865-1dbe-46ba-8cd9-65a3b13c74d6
      version: -1
      name: Detonate URL - McAfee ATD
      description: Detonates a URL using the McAfee Advanced Threat Defense sandbox
        integration.
      playbookName: Detonate URL - McAfee ATD
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      URL:
        complex:
          root: inputs.URL
          accessor: Data
      interval:
        simple: "1"
      timeout:
        simple: "15"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 195
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 1aaf0acd-d983-42a7-8ca3-50c3423b22d2
    type: playbook
    task:
      id: 1aaf0acd-d983-42a7-8ca3-50c3423b22d2
      version: -1
      name: Detonate URL - JoeSecurity
      description: |-
        Detonates one or more URLs using the Joe Security sandbox integration.
        Returns relevant reports to the War Room and url reputations to the context data.
      playbookName: Detonate URL - JoeSecurity
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      URL:
        complex:
          root: inputs.URL
          accessor: Data
      comments: {}
      internet-access:
        simple: "True"
      interval:
        simple: "1"
      report-file-type:
        simple: html
      systems: {}
      timeout:
        simple: "15"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 2b121169-8285-479f-8bd2-5c356bcef363
    type: playbook
    task:
      id: 2b121169-8285-479f-8bd2-5c356bcef363
      version: -1
      name: Detonate URL - CrowdStrike
      description: Detonate one or more files using the Wildfire integration. This
        playbook returns relevant reports to the War Room and file reputations to
        the context data.
      playbookName: Detonate URL - CrowdStrike
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Url:
        complex:
          root: inputs.URL
          accessor: Data
      environmentID:
        simple: "100"
      interval:
        simple: "5"
      timeout:
        simple: "30"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 1660,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: URL
  value:
    complex:
      root: URL
  required: false
  description: URL object of url to be detonated.
outputs:
- contextPath: DBotScore
  description: The Indicator's object
  type: unknown
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
- contextPath: File.SHA1
  description: SHA1 of the file
  type: string
- contextPath: File.MD5
  description: MD5 of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File
  description: The File's object
  type: unknown
- contextPath: File.SHA256
  description: SHA256 of the file
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: File.Type
  description: File type e.g. "PE" (only in case of report type=json)
  type: string
- contextPath: File.Size
  description: File size (only in case of report type=json)
  type: number
- contextPath: File.Name
  description: Filename (only in case of report type=json)
  type: string
releaseNotes: "New generic detonation playbook for URL"